/* Références supplémentaires identifiées : voir docs/catalogue-sources.md.
 * Les budgets sont des repères, pas des prix Amazon actualisés.
 * Aucune disponibilité en temps réel n'est garantie. Pas de photographie produit inventée.
 */
'use strict';
const EXTRA_GIFTS = [
  {
    "id": 166,
    "titre": "Perceuse-visseuse Bosch EasyDrill 1200",
    "emoji": "🔨",
    "desc": "Pour monter des meubles et réaliser de petits projets de bricolage. Vérifiez les accessoires et la batterie inclus dans l’offre choisie.",
    "genre": [
      "homme",
      "femme"
    ],
    "age": [
      "18-25",
      "26-35",
      "36-50",
      "50+"
    ],
    "budget": "50-100",
    "interets": [
      "bricolage"
    ],
    "originalite": 7,
    "family": "perceuse",
    "traits": [
      "utile",
      "pratique"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B08CVT3QKL?tag=trouvetonca05-21"
  },
  {
    "id": 167,
    "titre": "Kit d’arrosage Gardena Micro-Drip S 13010-20",
    "emoji": "🌱",
    "desc": "Un équipement pour arroser une rangée de plantes. À offrir si la personne dispose d’un point d’eau adapté et souhaite organiser son arrosage.",
    "genre": [
      "homme",
      "femme",
      "couple"
    ],
    "age": [
      "18-25",
      "26-35",
      "36-50",
      "50+"
    ],
    "budget": "20-50",
    "interets": [
      "jardinage"
    ],
    "originalite": 7,
    "family": "arrosage",
    "traits": [
      "utile",
      "pratique"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B018E0L5RY?tag=trouvetonca05-21"
  },
  {
    "id": 168,
    "titre": "Adaptateur diagnostic Veepeak OBDCheck BLE",
    "emoji": "🚗",
    "desc": "Pour un amateur automobile qui souhaite consulter les données de son véhicule. Vérifiez la compatibilité véhicule et application ; certaines applications sont payantes.",
    "genre": [
      "homme",
      "femme"
    ],
    "age": [
      "18-25",
      "26-35",
      "36-50",
      "50+"
    ],
    "budget": "20-50",
    "interets": [
      "auto-moto",
      "technologie"
    ],
    "originalite": 8,
    "family": "diagnostic-auto",
    "traits": [
      "utile",
      "passion"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B073XKQQQW?tag=trouvetonca05-21"
  },
  {
    "id": 169,
    "titre": "Machine à coudre Brother JX17FE",
    "emoji": "🧵",
    "desc": "Pour démarrer des projets de couture et des retouches à la maison. Prévoir un espace de travail et vérifier les tissus adaptés dans la notice.",
    "genre": [
      "homme",
      "femme",
      "couple"
    ],
    "age": [
      "18-25",
      "26-35",
      "36-50",
      "50+"
    ],
    "budget": ">100",
    "interets": [
      "creatif-diy"
    ],
    "originalite": 8,
    "family": "couture",
    "traits": [
      "creatif",
      "experience_maison"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B07W7YZJQH?tag=trouvetonca05-21"
  },
  {
    "id": 170,
    "titre": "Trépied smartphone Amazon Basics 127 cm",
    "emoji": "📷",
    "desc": "Pour des photos de groupe ou des prises de vue fixes au téléphone. Vérifiez les dimensions compatibles du support avant de choisir.",
    "genre": [
      "homme",
      "femme"
    ],
    "age": [
      "18-25",
      "26-35",
      "36-50",
      "50+"
    ],
    "budget": "<20",
    "interets": [
      "photo-video",
      "voyage"
    ],
    "originalite": 6,
    "family": "trepied-nomade",
    "traits": [
      "utile",
      "pratique"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B07MLHVBBC?tag=trouvetonca05-21"
  },
  {
    "id": 171,
    "titre": "Éclairage annulaire PEYOU 12 pouces avec trépied",
    "emoji": "💡",
    "desc": "Un éclairage pour filmer ou photographier chez soi. Utile pour des tutoriels créatifs ; prévoyez la place nécessaire pour le pied.",
    "genre": [
      "homme",
      "femme"
    ],
    "age": [
      "18-25",
      "26-35",
      "36-50",
      "50+"
    ],
    "budget": "20-50",
    "interets": [
      "photo-video",
      "creatif-diy"
    ],
    "originalite": 7,
    "family": "eclairage-photo",
    "traits": [
      "utile",
      "creatif"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B0CDKRXCK9?tag=trouvetonca05-21"
  },
  {
    "id": 172,
    "titre": "Support vidéo horizontal Elitehood 180 cm",
    "emoji": "🎬",
    "desc": "Pour filmer un plan de travail et montrer une recette ou une création. Vérifiez le poids et les dimensions du téléphone ainsi que l’espace disponible.",
    "genre": [
      "homme",
      "femme",
      "couple"
    ],
    "age": [
      "18-25",
      "26-35",
      "36-50",
      "50+"
    ],
    "budget": "50-100",
    "interets": [
      "photo-video",
      "creatif-diy",
      "cuisine"
    ],
    "originalite": 8,
    "family": "support-video-plongee",
    "traits": [
      "utile",
      "creatif"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B0CG18CQ7B?tag=trouvetonca05-21"
  },
  {
    "id": 173,
    "titre": "Jumelles enfant Buki BN009",
    "emoji": "🔭",
    "desc": "Pour observer les oiseaux et les paysages lors des sorties accompagnées. À partir de 8 ans pour cette sélection ; ne jamais regarder le soleil.",
    "genre": [
      "enfant"
    ],
    "age": [
      "8-12",
      "13-17"
    ],
    "budget": "<20",
    "interets": [
      "nature-outdoor",
      "animaux"
    ],
    "originalite": 7,
    "family": "jumelles-enfant",
    "traits": [
      "decouverte",
      "passion"
    ],
    "image": "",
    "imageFallback": true,
    "affiliateLink": "https://www.amazon.fr/dp/B001769J4E?tag=trouvetonca05-21"
  }
,
  // Passe 1.5 — lot A : bricolage et automobile (sources documentées).
  {"id":174,"titre":"Kit d’outils Hi-Spec 25 pièces","emoji":"🔨","desc":"De quoi effectuer les petites réparations du quotidien, dans un étui compact à garder à portée de main.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["bricolage"],"originalite":7,"asin":"B0DQ87YRBL","univers":"bricolage","family":"outillage-main","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DQ87YRBL?tag=trouvetonca05-21"},
  {"id":175,"titre":"Tournevis de précision JOREST 52 en 1","emoji":"🔨","desc":"Pour qui aime réparer ses petits appareils et démonter soigneusement leur boîtier. Vérifier les embouts nécessaires et les conditions de garantie.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["bricolage","technologie"],"originalite":7,"asin":"B0D633J3C7","univers":"bricolage","family":"tournevis-precision","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0D633J3C7?tag=trouvetonca05-21"},
  {"id":176,"titre":"Aimant télescopique éclairant BIIB","emoji":"🔨","desc":"Pour récupérer une vis tombée derrière un meuble ou dans un recoin du garage sans tout déplacer.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["bricolage","auto-moto"],"originalite":7,"asin":"B099K79ZPP","univers":"bricolage","family":"ramasse-vis","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B099K79ZPP?tag=trouvetonca05-21"},
  {"id":177,"titre":"Jauge de contour assemblable JOREST","emoji":"🔨","desc":"Elle aide à reporter le contour d’un obstacle sur une pièce à découper lors de la pose de parquet ou de travaux d’aménagement.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["bricolage"],"originalite":7,"asin":"B0969G39FL","univers":"bricolage","family":"jauge-contour","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0969G39FL?tag=trouvetonca05-21"},
  {"id":178,"titre":"Sac à outils enroulable Hinshark","emoji":"🔨","desc":"Un rangement à dérouler pour retrouver ses outils pendant une réparation puis les transporter facilement. Outils non fournis.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["bricolage","auto-moto"],"originalite":7,"asin":"B0FJF61PNY","univers":"bricolage","family":"rangement-outils","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0FJF61PNY?tag=trouvetonca05-21"},
  {"id":179,"titre":"Télémètre Bosch UniversalDistance 50 C","emoji":"🔨","desc":"Pour relever les dimensions d’une pièce et préparer ses projets d’aménagement sans dérouler un long mètre.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B0CFVZ5V5T","univers":"bricolage","family":"telemetre","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CFVZ5V5T?tag=trouvetonca05-21"},
  {"id":180,"titre":"Laser lignes Bosch Quigo avec pince MM 2","emoji":"🔨","desc":"Un repère lumineux pour aligner des étagères ou des cadres lors d’un projet de décoration. Ne pas diriger le laser vers les yeux.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["bricolage"],"originalite":7,"asin":"B0CGXSPRWP","univers":"bricolage","family":"niveau-laser","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CGXSPRWP?tag=trouvetonca05-21"},
  {"id":181,"titre":"Humidimètre à bois Bosch UniversalHumid","emoji":"🔨","desc":"Pour contrôler le bois avant un projet de menuiserie ou suivre son séchage. Un outil ciblé pour une personne qui travaille ce matériau.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["bricolage"],"originalite":7,"asin":"B0CFVXF4G2","univers":"bricolage","family":"humidimetre-bois","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CFVXF4G2?tag=trouvetonca05-21"},
  {"id":182,"titre":"Mesureur d’angle Bosch UniversalAngle","emoji":"🔨","desc":"Pour relever et reporter un angle avant une découpe : un complément utile à l’atelier pour les projets de menuiserie.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B0CFVYPQRB","univers":"bricolage","family":"mesure-angle","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CFVYPQRB?tag=trouvetonca05-21"},
  {"id":183,"titre":"Détecteur mural Bosch GMS 120-27","emoji":"🔨","desc":"Pour préparer un perçage en recherchant les matériaux cachés dans la paroi. Respecter la notice : une détection ne garantit jamais l’absence de danger.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["bricolage"],"originalite":7,"asin":"B0D94PBFF7","univers":"bricolage","family":"detecteur-mural","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0D94PBFF7?tag=trouvetonca05-21"},
  {"id":184,"titre":"Coffret Bosch X-Line 50 forets et embouts","emoji":"🔨","desc":"Un complément pour une personne qui possède déjà une perceuse et alterne montage et petits travaux. Vérifier la compatibilité du mandrin.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["bricolage"],"originalite":7,"asin":"B000P4IQF2","univers":"bricolage","family":"accessoires-perceuse","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B000P4IQF2?tag=trouvetonca05-21"},
  {"id":185,"titre":"Niveau à bulle Bosch 60 cm","emoji":"🔨","desc":"Pour poser droit une étagère, un cadre ou un élément de mobilier, avec des curseurs pour faciliter le marquage.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["bricolage"],"originalite":7,"asin":"B0DC6VPJCZ","univers":"bricolage","family":"niveau-bulle","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DC6VPJCZ?tag=trouvetonca05-21"},
  {"id":186,"titre":"Pied à coulisse Spurtar 150 mm","emoji":"🔨","desc":"Pour mesurer les petites pièces avec plus de finesse qu’une règle et préparer des assemblages à l’atelier.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["bricolage"],"originalite":7,"asin":"B074HZ8S21","univers":"bricolage","family":"pied-coulisse","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B074HZ8S21?tag=trouvetonca05-21"},
  {"id":187,"titre":"Aspirateur automobile BLACK+DECKER PD1200AV","emoji":"🚗","desc":"Son flexible aide à atteindre les recoins de l’habitacle. Fonctionne sur prise automobile 12 V : vérifier l’équipement du véhicule.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["auto-moto"],"originalite":7,"asin":"B015FO9XF8","univers":"auto-moto","family":"aspirateur-auto","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B015FO9XF8?tag=trouvetonca05-21"},
  {"id":188,"titre":"Coffret entretien automobile CarPlan Demon","emoji":"🚗","desc":"Pour une personne qui apprécie de soigner sa voiture, avec plusieurs produits dédiés à l’entretien. Respecter les surfaces compatibles et les précautions des flacons.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["auto-moto"],"originalite":7,"asin":"B07Q44K5V8","univers":"auto-moto","family":"detailing-auto","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07Q44K5V8?tag=trouvetonca05-21"},
  {"id":189,"titre":"Kit de nettoyage intérieur de pare-brise télescopique","emoji":"🚗","desc":"Une tête orientable pour atteindre le bas du pare-brise depuis l’habitacle, avec des tampons lavables à réutiliser.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["auto-moto"],"originalite":7,"asin":"B0DZX3GDPP","univers":"auto-moto","family":"nettoyage-vitres-auto","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DZX3GDPP?tag=trouvetonca05-21"},
  {"id":190,"titre":"Balai microfibre télescopique WillingHeart","emoji":"🚗","desc":"Pour atteindre plus facilement le toit et les grandes surfaces d’un véhicule pendant le lavage. Rincer les fibres pour éviter de retenir des grains abrasifs.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["auto-moto"],"originalite":7,"asin":"B08FDJXJLN","univers":"auto-moto","family":"balai-lavage-auto","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08FDJXJLN?tag=trouvetonca05-21"},
  {"id":191,"titre":"Support smartphone automobile Miracase","emoji":"🚗","desc":"Pour installer le téléphone comme aide à la navigation. Vérifier le support adapté au véhicule et le régler avant de prendre la route.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["auto-moto","voyage"],"originalite":7,"asin":"B0CB1C69BY","univers":"auto-moto","family":"support-telephone-auto","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CB1C69BY?tag=trouvetonca05-21"},
  {"id":192,"titre":"Organiseur de coffre FORTEM 50 L","emoji":"🚗","desc":"Pour séparer les affaires de route, les courses et le matériel de sortie dans le coffre. Vérifier les dimensions et utiliser les fixations prévues.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["auto-moto","voyage"],"originalite":7,"asin":"B01DIMTWCS","univers":"auto-moto","family":"organiseur-coffre","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01DIMTWCS?tag=trouvetonca05-21"},
  {"id":193,"titre":"Transmetteur FM Bluetooth LENCENT","emoji":"🚗","desc":"Pour écouter sa musique sur un ancien autoradio grâce à une fréquence FM. Vérifier la prise du véhicule et préparer les réglages à l’arrêt.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["auto-moto","musique"],"originalite":7,"asin":"B07VFT4D6B","univers":"auto-moto","family":"transmetteur-fm","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07VFT4D6B?tag=trouvetonca05-21"},
  {"id":194,"titre":"Housse de banquette pour chien KYG","emoji":"🚗","desc":"Pour protéger la banquette lors des sorties avec le chien. Vérifier les dimensions ; cette housse ne remplace pas un dispositif de retenue adapté.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["auto-moto","animaux","voyage"],"originalite":7,"asin":"B07S1NJBGW","univers":"auto-moto","family":"housse-auto-animaux","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07S1NJBGW?tag=trouvetonca05-21"},
  {"id":195,"titre":"Clip porte-lunettes de voiture JEJA","emoji":"🚗","desc":"Un petit accessoire pour garder ses lunettes accessibles sur le pare-soleil au lieu de les chercher dans la boîte à gants.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["auto-moto"],"originalite":7,"asin":"B0BX316GFJ","univers":"auto-moto","family":"rangement-lunettes-auto","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0BX316GFJ?tag=trouvetonca05-21"},
  {"id":196,"titre":"Filets de rangement EINESIN pour van","emoji":"🚗","desc":"Pour organiser les petits objets à bord d’un van ou camping-car. Vérifier les dimensions et le mode de fixation avant de l’offrir.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["auto-moto","voyage","nature-outdoor"],"originalite":7,"asin":"B09V723HDN","univers":"auto-moto","family":"rangement-van","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B09V723HDN?tag=trouvetonca05-21"},
  {"id":197,"titre":"Pompe rechargeable Bosch EasyPump","emoji":"🚗","desc":"Pour remettre à pression les pneus de vélo ou de voiture et préparer ses sorties. Vérifier les valves compatibles et suivre la pression prescrite pour chaque équipement.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["auto-moto","sport"],"originalite":7,"asin":"B08HQHW4LS","univers":"auto-moto","family":"gonfleur-pneus","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08HQHW4LS?tag=trouvetonca05-21"},
  {"id":198,"titre":"Compresseur d’atelier Stanley DN200/10/5","emoji":"🔨","desc":"Pour équiper un petit atelier en air comprimé. Prévoir une prise secteur, de la place et les accessoires compatibles ; ce n’est pas un simple gonfleur de poche.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["bricolage","auto-moto"],"originalite":7,"asin":"B00GN89EQE","univers":"bricolage","family":"compresseur-atelier","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00GN89EQE?tag=trouvetonca05-21"},
  {"id":199,"titre":"Booster automobile NOCO Boost GB40","emoji":"🚗","desc":"Un équipement à garder pour les imprévus de batterie. Réservé aux véhicules et batteries compatibles selon la notice, à consulter avant toute utilisation.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["auto-moto"],"originalite":7,"asin":"B015TKUPIC","univers":"auto-moto","family":"booster-batterie","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B015TKUPIC?tag=trouvetonca05-21"},
  {"id":200,"titre":"Chargeur fixe NOCO GENIUS2D","emoji":"🚗","desc":"Pour entretenir la batterie d’un véhicule peu utilisé. Son montage fixe et sa compatibilité avec les batteries plomb 12 V doivent être vérifiés avant l’achat.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["auto-moto"],"originalite":7,"asin":"B087XHDPPM","univers":"auto-moto","family":"chargeur-batterie","traits":["utile","pratique","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B087XHDPPM?tag=trouvetonca05-21"}
,
  // Passe 1.5 — lot B : jardinage et maison.
  {"id":201,"titre":"Coffret d’outils de jardin YAUNGEL","emoji":"🌱","desc":"Pour rempoter, planter et entretenir un petit jardin avec ses outils regroupés dans un sac.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B09FB2RT1G","univers":"jardinage","family":"outils-jardin","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B09FB2RT1G?tag=trouvetonca05-21"},
  {"id":202,"titre":"Boîte de rangement pour semences à 40 emplacements","emoji":"🌱","desc":"Pour classer ses sachets de graines par variété et préparer les semis de la prochaine saison. Graines non incluses.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B0C9PV1HXF","univers":"jardinage","family":"rangement-semences","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0C9PV1HXF?tag=trouvetonca05-21"},
  {"id":203,"titre":"Agenouilloir de jardin pliable Relaxdays","emoji":"🌱","desc":"Un support rembourré pour les travaux près du sol, avec des poches pour garder les outils accessibles. Vérifier les dimensions et limites de charge.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B07TF9X42H","univers":"jardinage","family":"agenouilloir","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07TF9X42H?tag=trouvetonca05-21"},
  {"id":204,"titre":"Graines de 12 herbes aromatiques HERBAL AGE","emoji":"🌱","desc":"Pour semer ensemble des aromatiques à utiliser ensuite en cuisine. Prévoir pots, terreau et un emplacement adapté ; la germination dépend des conditions de culture.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["jardinage","cuisine"],"originalite":7,"asin":"B08KGCRF58","univers":"jardinage","family":"graines-aromatiques","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08KGCRF58?tag=trouvetonca05-21"},
  {"id":205,"titre":"Étiquettes de jardin en T","emoji":"🌱","desc":"Pour identifier ses semis et distinguer les variétés au potager. Un petit cadeau utile pour une personne qui cultive déjà de nombreuses plantes.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["jardinage"],"originalite":7,"asin":"B09H334H9F","univers":"jardinage","family":"etiquettes-jardin","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B09H334H9F?tag=trouvetonca05-21"},
  {"id":206,"titre":"Ramasseur de baies Gardena 17400-20","emoji":"🌱","desc":"Pour faciliter la récolte des petits fruits dans le jardin. À offrir à quelqu’un qui cultive réellement des baies et peut utiliser ce type de peigne.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B0BNLP3VH1","univers":"jardinage","family":"recolte-baies","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0BNLP3VH1?tag=trouvetonca05-21"},
  {"id":207,"titre":"Kit pistolet et raccords Gardena Premium","emoji":"🌱","desc":"Pour équiper un tuyau existant et arroser les plantations à la main. Vérifier le diamètre du tuyau et le robinet avant de choisir.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B076WYHCRF","univers":"jardinage","family":"pistolet-arrosage","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B076WYHCRF?tag=trouvetonca05-21"},
  {"id":208,"titre":"Arroseur Gardena AquaZoom compact","emoji":"🌱","desc":"Pour arroser une zone du jardin sans rester avec le tuyau à la main. À réserver à un terrain et un point d’eau adaptés.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B07YSTGP17","univers":"jardinage","family":"arroseur-surface","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07YSTGP17?tag=trouvetonca05-21"},
  {"id":209,"titre":"Plantoir à bulbes Gardena","emoji":"🌱","desc":"Pour préparer les trous de plantation et composer les massifs de la prochaine floraison. Une attention utile pour les amateurs de bulbes.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["jardinage"],"originalite":7,"asin":"B0001E3W8W","univers":"jardinage","family":"plantoir-bulbes","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0001E3W8W?tag=trouvetonca05-21"},
  {"id":210,"titre":"Nettoyeur de joints Gardena combisystem 3 en 1","emoji":"🌱","desc":"Pour retirer manuellement mousse et herbes entre les dalles. Vérifier si un manche compatible doit être acheté séparément.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B08KGMS5XR","univers":"jardinage","family":"desherbage-joints","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08KGMS5XR?tag=trouvetonca05-21"},
  {"id":211,"titre":"Potager sur pieds tectake avec étagère","emoji":"🌱","desc":"Pour cultiver à deux quelques légumes ou aromatiques à hauteur confortable. Prévoir la place, le terreau et les contraintes de charge du support.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["jardinage"],"originalite":7,"asin":"B07W8VGSRZ","univers":"jardinage","family":"potager-sureleve","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07W8VGSRZ?tag=trouvetonca05-21"},
  {"id":212,"titre":"Composteur de jardin GARANTIA Thermo-King 900 L","emoji":"🌱","desc":"Pour un jardinier qui veut valoriser ses déchets végétaux et dispose d’un grand espace extérieur. Un équipement volumineux à offrir après avoir vérifié ce besoin.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["jardinage"],"originalite":7,"asin":"B0CW9S75Y1","univers":"jardinage","family":"composteur","traits":["utile","pratique"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CW9S75Y1?tag=trouvetonca05-21"},
  {"id":213,"titre":"Fontaine d’intérieur Zen’Light Kini","emoji":"🏠","desc":"Une petite fontaine de table pour les personnes qui aiment le bruit de l’eau. Prévoir une prise et un entretien régulier, sans promesse d’effet thérapeutique.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["maison-deco"],"originalite":7,"asin":"B07PP8C41F","univers":"maison-deco","family":"fontaine-interieur","traits":["decoration"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07PP8C41F?tag=trouvetonca05-21"},
  {"id":214,"titre":"Jardin zen miniature Atmosphera","emoji":"🏠","desc":"Un petit paysage à installer sur un bureau et à réorganiser pour une pause créative. Objet décoratif, à tenir hors de portée des jeunes enfants.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["maison-deco"],"originalite":7,"asin":"B01AC217LQ","univers":"maison-deco","family":"jardin-zen","traits":["decoration"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01AC217LQ?tag=trouvetonca05-21"},
  {"id":215,"titre":"LEGO Botanicals Bambou de la Chance 10344","emoji":"🏠","desc":"Une plante à construire puis à exposer, sans arrosage. Une petite activité à partager pour les adultes qui aiment assembler et décorer.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["maison-deco","creatif-diy"],"originalite":7,"asin":"B01N9D9U4O","univers":"maison-deco","family":"construction-botanique","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01N9D9U4O?tag=trouvetonca05-21"},
  {"id":216,"titre":"Pêle-mêle mural Uping à pinces","emoji":"🏠","desc":"Pour choisir ensemble ses photos et souvenirs de voyage, puis les afficher sans commander de tirage encadré sur mesure.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["maison-deco","photo-video"],"originalite":7,"asin":"B07Q3QHL8V","univers":"maison-deco","family":"pele-mele","traits":["sentimental","decoration"],"occasions":["anniv","noel","valentin"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07Q3QHL8V?tag=trouvetonca05-21"},
  {"id":217,"titre":"Tableau de sable mobile SANDCLE","emoji":"🏠","desc":"Le sable compose un nouveau paysage quand on retourne le cadre. Une décoration à contempler sur un bureau ou une étagère.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["maison-deco"],"originalite":7,"asin":"B0BDKNCS6W","univers":"maison-deco","family":"tableau-sable","traits":["decoration"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0BDKNCS6W?tag=trouvetonca05-21"},
  {"id":218,"titre":"Duo d’éléphants en céramique Pajoma","emoji":"🏠","desc":"Deux silhouettes assorties pour un couple qui apprécie les objets symboliques et les décorations animalières.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["maison-deco","animaux"],"originalite":7,"asin":"B008YUMLX2","univers":"maison-deco","family":"statuette-couple","traits":["sentimental","decoration"],"occasions":["anniv","noel","valentin"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B008YUMLX2?tag=trouvetonca05-21"},
  {"id":219,"titre":"Trio de miroirs muraux BONNYCO","emoji":"🏠","desc":"Pour composer un petit ensemble mural et habiller une entrée ou une chambre. Vérifier les dimensions et les fixations adaptées au mur.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["maison-deco"],"originalite":7,"asin":"B07T31R5F4","univers":"maison-deco","family":"miroirs-decoratifs","traits":["decoration"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07T31R5F4?tag=trouvetonca05-21"},
  {"id":220,"titre":"Coffret de bols japonais Maneki Neko","emoji":"🏠","desc":"Pour dresser une table aux motifs japonais et partager un repas maison. Un cadeau concret pour les amateurs de vaisselle illustrée.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["cuisine","maison-deco"],"originalite":7,"asin":"B00CD16UT4","univers":"cuisine","family":"bols-japonais","traits":["decoration"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00CD16UT4?tag=trouvetonca05-21"},
  {"id":221,"titre":"Maquette en bois ROWOOD Pavillon Sakura","emoji":"🏠","desc":"Un petit pavillon à assembler patiemment puis à exposer. À partager à deux pour une soirée manuelle ; vérifier les outils et consommables requis.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["creatif-diy","maison-deco"],"originalite":7,"asin":"B0GT8ZFTW4","univers":"creatif-diy","family":"maquette-bois","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0GT8ZFTW4?tag=trouvetonca05-21"},
  {"id":222,"titre":"Lampe chauffe-bougie avec minuterie","emoji":"🏠","desc":"Pour une personne qui possède déjà des bougies en pot compatibles et souhaite les utiliser sans allumer la mèche. Reste un appareil chauffant à utiliser selon la notice.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["maison-deco"],"originalite":7,"asin":"B0DJW6G93W","univers":"maison-deco","family":"chauffe-bougie","traits":["decoration"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DJW6G93W?tag=trouvetonca05-21"}
,
  // Passe 1.5 — lot C : enfants et activités à deux.
  {"id":223,"titre":"Jardin miniature Ecoiffier 4585","emoji":"🧸","desc":"Pour imiter les travaux du jardin avec une brouette et ses accessoires. Dès 18 mois, sous surveillance ; ne convient pas aux plus petits.","genre":["enfant"],"age":["0-3","4-7"],"budget":"20-50","interets":["jardinage"],"originalite":7,"asin":"B0BSV5D8HM","univers":"jardinage","family":"jardinage-imitation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0BSV5D8HM?tag=trouvetonca05-21"},
  {"id":224,"titre":"Balle souple Oball Classic","emoji":"🧸","desc":"Une balle ajourée facile à saisir pour les premiers jeux accompagnés. Modèle annoncé dès la naissance ; suivre les consignes du fabricant.","genre":["enfant"],"age":["0-3"],"budget":"<20","interets":[],"originalite":7,"asin":"B00ZRD99C0","univers":"eveil","family":"balle-eveil","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00ZRD99C0?tag=trouvetonca05-21"},
  {"id":225,"titre":"Livre musical Fisher-Price Comptines CDH39","emoji":"🧸","desc":"Pour découvrir les comptines et manipuler des pages avec un adulte. Vérifier l’âge minimal sur la notice et sécuriser le compartiment des piles.","genre":["enfant"],"age":["0-3"],"budget":"<20","interets":["lecture","musique"],"originalite":7,"asin":"B010X18T0I","univers":"lecture","family":"livre-musical","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B010X18T0I?tag=trouvetonca05-21"},
  {"id":226,"titre":"Cube de manipulation LUDI","emoji":"🧸","desc":"Pour glisser et récupérer les balles à travers les élastiques. Dès 10 mois, avec un adulte ; pas un jouet de naissance.","genre":["enfant"],"age":["0-3"],"budget":"<20","interets":[],"originalite":7,"asin":"B09WRG5PFD","univers":"eveil","family":"manipulation-eveil","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B09WRG5PFD?tag=trouvetonca05-21"},
  {"id":227,"titre":"Tambourin lumineux VTech Lumi Tambourin","emoji":"🧸","desc":"Un premier instrument à secouer et écouter pendant les moments d’éveil. Dès 3 mois, sous surveillance.","genre":["enfant"],"age":["0-3"],"budget":"<20","interets":["musique"],"originalite":7,"asin":"B0CQ5JQPX6","univers":"musique","family":"tambourin-eveil","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CQ5JQPX6?tag=trouvetonca05-21"},
  {"id":228,"titre":"Premières briques Ecoiffier BB Abrick","emoji":"🧸","desc":"De grosses briques pour les premières constructions et démolitions accompagnées. Dès 12 mois : vérifier l’âge réel de l’enfant avant de choisir.","genre":["enfant"],"age":["0-3"],"budget":"<20","interets":["creatif-diy"],"originalite":7,"asin":"B0BVBKGHQZ","univers":"creatif-diy","family":"briques-eveil","traits":["creatif","decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0BVBKGHQZ?tag=trouvetonca05-21"},
  {"id":229,"titre":"Coffret naissance VTech Éveil des Sens","emoji":"🧸","desc":"Plusieurs premiers jouets pour varier les découvertes accompagnées. Suivre l’âge et les précautions propres à chaque élément ; ne pas laisser de jouets dans l’espace de sommeil.","genre":["enfant"],"age":["0-3"],"budget":"20-50","interets":["musique","animaux"],"originalite":7,"asin":"B07PF19MBT","univers":"musique","family":"coffret-eveil","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07PF19MBT?tag=trouvetonca05-21"},
  {"id":230,"titre":"Spirale d’activités Nuby Animal Adventures","emoji":"🧸","desc":"Des éléments à observer et toucher pendant les sorties accompagnées. Modèle annoncé dès la naissance ; respecter les fixations et retirer l’ensemble lorsque la notice le demande.","genre":["enfant"],"age":["0-3"],"budget":"<20","interets":["animaux"],"originalite":7,"asin":"B0BH4X6CZH","univers":"animaux","family":"spirale-eveil","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0BH4X6CZH?tag=trouvetonca05-21"},
  {"id":231,"titre":"Trieur de formes Fisher-Price","emoji":"🧸","desc":"Pour essayer d’associer une forme à son ouverture au fil des jeux avec un adulte. Vérifier l’âge minimal indiqué sur l’emballage.","genre":["enfant"],"age":["0-3"],"budget":"<20","interets":[],"originalite":7,"asin":"B01NCUSC7V","univers":"eveil","family":"tri-formes","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01NCUSC7V?tag=trouvetonca05-21"},
  {"id":232,"titre":"Jeu Pic Pirate TOMY","emoji":"🧸","desc":"Chacun insère une épée à son tour en attendant que le pirate bondisse. Un jeu simple à partager en famille, dès 4 ans.","genre":["enfant"],"age":["4-7","8-12"],"budget":"<20","interets":[],"originalite":7,"asin":"B00000JICB","univers":"eveil","family":"jeu-adresse","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00000JICB?tag=trouvetonca05-21"},
  {"id":233,"titre":"Mosaïques Nathan Clic’Educ","emoji":"🧸","desc":"Pour composer des motifs colorés et exercer sa précision en s’amusant. Dès 4 ans ; ranger les petites pièces après l’activité.","genre":["enfant"],"age":["4-7"],"budget":"20-50","interets":["creatif-diy"],"originalite":7,"asin":"B01N4V5KDA","univers":"creatif-diy","family":"mosaique-enfant","traits":["creatif","decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01N4V5KDA?tag=trouvetonca05-21"},
  {"id":234,"titre":"Jeu de cartes UNO Junior","emoji":"🧸","desc":"Une version accessible du jeu de cartes pour apprendre à attendre son tour et jouer ensemble. Sélection proposée dès 4 ans, modèle annoncé dès 3 ans.","genre":["enfant"],"age":["4-7"],"budget":"<20","interets":[],"originalite":7,"asin":"B07Y94Y3JL","univers":"eveil","family":"cartes-enfant","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07Y94Y3JL?tag=trouvetonca05-21"},
  {"id":235,"titre":"Mon labo d’écriture HEADU Montessori","emoji":"🧸","desc":"Pour explorer les lettres avec un adulte, sans transformer le cadeau en exercice scolaire. À adapter au rythme et aux acquis de l’enfant.","genre":["enfant"],"age":["4-7"],"budget":"<20","interets":["lecture"],"originalite":7,"asin":"B09TR4XK33","univers":"lecture","family":"ecriture-enfant","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B09TR4XK33?tag=trouvetonca05-21"},
  {"id":236,"titre":"Dinosaures à assembler Dreamon","emoji":"🧸","desc":"Pour démonter et reconstruire des dinosaures avec des outils de jeu. Proposé dès 4 ans, sous surveillance, en respectant la notice.","genre":["enfant"],"age":["4-7","8-12"],"budget":"20-50","interets":["bricolage","animaux"],"originalite":7,"asin":"B08PBK29H2","univers":"bricolage","family":"construction-dinosaure","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08PBK29H2?tag=trouvetonca05-21"},
  {"id":237,"titre":"Cahier de peinture à l’eau JoyCat","emoji":"🧸","desc":"Des illustrations à colorer avec l’eau et les peintures du kit. Une activité calme et accompagnée, proposée ici dès 4 ans.","genre":["enfant"],"age":["4-7"],"budget":"<20","interets":["creatif-diy"],"originalite":7,"asin":"B0CTHQJF57","univers":"creatif-diy","family":"peinture-enfant","traits":["creatif","decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CTHQJF57?tag=trouvetonca05-21"},
  {"id":238,"titre":"Bras hydraulique à construire Buki 7505","emoji":"🧸","desc":"Pour assembler puis piloter un bras fonctionnant avec de l’eau. Le fabricant indique dès 10 ans : retenu uniquement en 13–17 ans pour ne pas le proposer aux enfants de 8 ans.","genre":["enfant"],"age":["13-17"],"budget":"20-50","interets":["bricolage","technologie"],"originalite":7,"asin":"B071FSNTMS","univers":"bricolage","family":"mecanique-hydraulique","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B071FSNTMS?tag=trouvetonca05-21"},
  {"id":239,"titre":"Bracelets d’amitié Buki BE102","emoji":"🧸","desc":"Pour apprendre des tressages colorés et offrir ses propres bracelets aux amis. Dès 8 ans ; une activité qui demande un peu de patience.","genre":["enfant"],"age":["8-12","13-17"],"budget":"<20","interets":["creatif-diy"],"originalite":7,"asin":"B01MYGUOQ5","univers":"creatif-diy","family":"tissage-bracelets","traits":["creatif","decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01MYGUOQ5?tag=trouvetonca05-21"},
  {"id":240,"titre":"Coffret tricot Buki BE002","emoji":"🧸","desc":"Pour découvrir les premiers gestes du tricot et réaliser un petit projet manuel. Dès 8 ans, avec l’aide d’un adulte pour démarrer si nécessaire.","genre":["enfant"],"age":["8-12","13-17"],"budget":"<20","interets":["creatif-diy"],"originalite":7,"asin":"B071DVDSLY","univers":"creatif-diy","family":"tricot","traits":["creatif","decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B071DVDSLY?tag=trouvetonca05-21"},
  {"id":241,"titre":"Coffret randonnée nature Buki BN014","emoji":"🧸","desc":"Pour préparer une sortie accompagnée avec boussole et accessoires d’observation. Retenu dès 8 ans ; ne jamais regarder le soleil avec les jumelles.","genre":["enfant"],"age":["8-12"],"budget":"<20","interets":["nature-outdoor","voyage"],"originalite":7,"asin":"B09598BXNN","univers":"nature-outdoor","family":"exploration-enfant","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B09598BXNN?tag=trouvetonca05-21"},
  {"id":242,"titre":"Électronique expert Buki 7160","emoji":"🧸","desc":"Pour monter des circuits sans soudure et observer leurs effets. Dès 8 ans, en suivant les montages de la notice avec un adulte.","genre":["enfant"],"age":["8-12","13-17"],"budget":"20-50","interets":["technologie","bricolage"],"originalite":7,"asin":"B071FSNTMQ","univers":"technologie","family":"electronique-educative","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B071FSNTMQ?tag=trouvetonca05-21"},
  {"id":243,"titre":"Terrarium Buki BL034","emoji":"🧸","desc":"Pour créer un petit environnement végétal et suivre son évolution. Proposé dès 8 ans, modèle annoncé dès 6 ans ; vérifier le contenu et les consignes du kit.","genre":["enfant"],"age":["8-12"],"budget":"<20","interets":["jardinage","nature-outdoor"],"originalite":7,"asin":"B0CP88GJQ5","univers":"jardinage","family":"terrarium","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CP88GJQ5?tag=trouvetonca05-21"},
  {"id":244,"titre":"Table d’activités nature VTech","emoji":"🧸","desc":"Plusieurs découvertes à explorer sur une même table. Dès 9 mois, selon les capacités de l’enfant ; prévoir l’espace nécessaire et surveiller le jeu.","genre":["enfant"],"age":["0-3"],"budget":"50-100","interets":["animaux","musique"],"originalite":7,"asin":"B0C86GM591","univers":"animaux","family":"table-eveil","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0C86GM591?tag=trouvetonca05-21"},
  {"id":245,"titre":"Appareil photo VTech KidiZoom Duo FX","emoji":"🧸","desc":"Pour prendre ses premières photos et imaginer de petits reportages. Version française annoncée de 4 à 12 ans ; accompagner l’enfant dans le respect de la vie privée.","genre":["enfant"],"age":["4-7","8-12"],"budget":"50-100","interets":["photo-video","technologie"],"originalite":7,"asin":"B0DT1FGBCP","univers":"photo-video","family":"photo-enfant","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DT1FGBCP?tag=trouvetonca05-21"},
  {"id":246,"titre":"Magi Bureau VTech interactif 6 en 1","emoji":"🧸","desc":"Un coin pour dessiner et explorer des activités avec un tabouret. Proposé dès 4 ans ; vérifier les dimensions et la place disponible.","genre":["enfant"],"age":["4-7"],"budget":"50-100","interets":["creatif-diy","lecture"],"originalite":7,"asin":"B0DSJVJK68","univers":"creatif-diy","family":"bureau-creatif-enfant","traits":["creatif","decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DSJVJK68?tag=trouvetonca05-21"},
  {"id":247,"titre":"Platine VTech DJ Studio Magic Light","emoji":"🧸","desc":"Pour jouer avec les rythmes et les effets sonores. Un instrument de jeu en français, retenu pour les 4–7 ans.","genre":["enfant"],"age":["4-7"],"budget":"20-50","interets":["musique"],"originalite":7,"asin":"B0DP2Z7Y27","univers":"musique","family":"mixage-enfant","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DP2Z7Y27?tag=trouvetonca05-21"},
  {"id":248,"titre":"Jeu de conversation Dimoi Couple","emoji":"🎁","desc":"Des questions pour prendre le temps de discuter à deux et découvrir de nouveaux sujets. Chacun reste libre de passer une carte.","genre":["couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":[],"originalite":7,"asin":"B08DG3539L","univers":"jeux-societe","family":"conversation-couple","traits":["sentimental","experience_maison"],"occasions":["anniv","noel","valentin"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08DG3539L?tag=trouvetonca05-21"},
  {"id":249,"titre":"Codenames Duo — version française","emoji":"🎁","desc":"Pour chercher ensemble des associations de mots et réussir une mission en coopération. Proposé aux adultes et adolescents de 13 ans et plus.","genre":["homme","femme","couple","enfant"],"age":["18-25","26-35","36-50","50+","13-17"],"budget":"20-50","interets":["lecture"],"originalite":7,"asin":"B076X5VSYM","univers":"lecture","family":"jeu-mots-cooperatif","traits":["decouverte","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B076X5VSYM?tag=trouvetonca05-21"},
  {"id":250,"titre":"7 Wonders Duel","emoji":"🎁","desc":"Un jeu conçu pour deux, où chacun développe sa civilisation. Pour un couple qui aime réfléchir et rejouer avec des stratégies différentes.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":[],"originalite":7,"asin":"B014DMSTXK","univers":"jeux-societe","family":"jeu-strategie-duel","traits":["decouverte","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B014DMSTXK?tag=trouvetonca05-21"},
  {"id":251,"titre":"Schotten Totten — version française","emoji":"🎁","desc":"Un duel de cartes compact pour les soirées à deux ou les vacances. Dès 8 ans, avec des règles à découvrir ensemble.","genre":["homme","femme","couple","enfant"],"age":["18-25","26-35","36-50","50+","8-12","13-17"],"budget":"<20","interets":[],"originalite":7,"asin":"B01IP4MVFY","univers":"jeux-societe","family":"jeu-cartes-tactique","traits":["decouverte","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01IP4MVFY?tag=trouvetonca05-21"},
  {"id":252,"titre":"Lacuna — jeu stratégique à deux","emoji":"🎁","desc":"Pour partager une partie de placement autour d’un plateau de fleurs. Dès 8 ans ; une autre façon de jouer en duo sans écran.","genre":["homme","femme","couple","enfant"],"age":["18-25","26-35","36-50","50+","8-12","13-17"],"budget":"20-50","interets":[],"originalite":7,"asin":"B0DVZD3MCX","univers":"jeux-societe","family":"jeu-placement-duel","traits":["decouverte","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DVZD3MCX?tag=trouvetonca05-21"},
  {"id":253,"titre":"Gaufrier Tefal Snack Time Happiness","emoji":"🎁","desc":"Pour préparer des gaufres et des croque-monsieur à partager. Prévoir la place et suivre les précautions d’un appareil chauffant.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["cuisine"],"originalite":7,"asin":"B0743K4GJL","univers":"cuisine","family":"gaufrier","traits":["decouverte","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0743K4GJL?tag=trouvetonca05-21"},
  {"id":254,"titre":"Crêpière Tefal Crep Party six empreintes","emoji":"🎁","desc":"Pour préparer de petites crêpes autour de la table et varier les garnitures à deux ou avec des proches. Utilisation par des adultes.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["cuisine"],"originalite":7,"asin":"B00ESZEI0Q","univers":"cuisine","family":"crepiere","traits":["decouverte","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00ESZEI0Q?tag=trouvetonca05-21"},
  {"id":255,"titre":"Grill et fondue thaï TomYang Hot Pot","emoji":"🎁","desc":"Pour découvrir un repas à composer ensemble autour d’un bouillon et d’un grill de table. Vérifier la place et les consignes de cuisson.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["cuisine"],"originalite":7,"asin":"B0141712VI","univers":"cuisine","family":"hotpot","traits":["decouverte","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0141712VI?tag=trouvetonca05-21"}
,
  // Passe 1.5 — lot D : plein air, photo et création.
  {"id":256,"titre":"Popote de camping OVERMONT 14 pièces","emoji":"🏕️","desc":"Pour préparer et partager un repas en camping avec un ensemble compact. Vérifier le contenu, la source de chaleur compatible et les précautions de cuisson.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["nature-outdoor","cuisine","voyage"],"originalite":7,"asin":"B07D6JCHKS","univers":"nature-outdoor","family":"popote-camping","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07D6JCHKS?tag=trouvetonca05-21"},
  {"id":257,"titre":"Matelas de camping gonflable TRINORDIC","emoji":"🏕️","desc":"Pour une nuit sous tente avec un couchage facile à transporter. Vérifier les dimensions et l’isolation adaptée à la saison prévue.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["nature-outdoor","voyage"],"originalite":7,"asin":"B07X6RCM9M","univers":"nature-outdoor","family":"matelas-camping","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07X6RCM9M?tag=trouvetonca05-21"},
  {"id":258,"titre":"Chaise de camping pliante TREKOLOGY","emoji":"🏕️","desc":"Pour s’asseoir au bivouac ou pendant une pause en plein air. Vérifier la charge maximale et les dimensions une fois repliée.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["nature-outdoor","voyage"],"originalite":7,"asin":"B07NT77GT8","univers":"nature-outdoor","family":"chaise-camping","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07NT77GT8?tag=trouvetonca05-21"},
  {"id":259,"titre":"Tapis d’assise pliable TRINORDIC","emoji":"🏕️","desc":"Un petit support pour les pauses sur un sol humide ou froid, facile à glisser dans un sac de randonnée.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["nature-outdoor","voyage"],"originalite":7,"asin":"B0C5G2XY13","univers":"nature-outdoor","family":"tapis-assise","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0C5G2XY13?tag=trouvetonca05-21"},
  {"id":260,"titre":"Douche solaire de camping 20 L","emoji":"🏕️","desc":"Pour les séjours en camping où l’on souhaite un point d’eau d’appoint. La température dépend du soleil : toujours vérifier l’eau avant usage.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["nature-outdoor","voyage"],"originalite":7,"asin":"B0C4B9B1YW","univers":"nature-outdoor","family":"douche-camping","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0C4B9B1YW?tag=trouvetonca05-21"},
  {"id":261,"titre":"Organiseurs de bagage compressibles LOONARA","emoji":"🏕️","desc":"Pour séparer vêtements et accessoires dans un sac ou une valise et retrouver ses affaires plus facilement à l’étape.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["nature-outdoor","voyage"],"originalite":7,"asin":"B0CQKC61RB","univers":"nature-outdoor","family":"organiseurs-bagage","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CQKC61RB?tag=trouvetonca05-21"},
  {"id":262,"titre":"Oreiller de camping gonflable compact","emoji":"🏕️","desc":"Pour compléter son couchage nomade sans transporter un oreiller de maison. À choisir selon le confort et les dimensions recherchés.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["nature-outdoor","voyage"],"originalite":7,"asin":"B0GF1PMTBW","univers":"nature-outdoor","family":"oreiller-camping","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0GF1PMTBW?tag=trouvetonca05-21"},
  {"id":263,"titre":"Kit de nettoyage photo K&F CONCEPT","emoji":"📷","desc":"Pour entretenir le matériel photo avec des accessoires dédiés. Utiliser chaque outil selon la notice ; ne pas improviser un nettoyage du capteur.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["photo-video"],"originalite":7,"asin":"B00JL4IWXI","univers":"photo-video","family":"entretien-photo","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00JL4IWXI?tag=trouvetonca05-21"},
  {"id":264,"titre":"Sac à dos photo K&F CONCEPT 30 L","emoji":"📷","desc":"Pour organiser boîtiers et objectifs lors des sorties. Vérifier les compartiments et le volume nécessaires au matériel de la personne.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["photo-video","voyage","nature-outdoor"],"originalite":7,"asin":"B0DT6F5LD2","univers":"photo-video","family":"sac-photo","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DT6F5LD2?tag=trouvetonca05-21"},
  {"id":265,"titre":"Réflecteur photo K&F CONCEPT 5 en 1","emoji":"📷","desc":"Pour modifier la lumière d’un portrait sans ajouter de lampe. Un accessoire à plier et emporter pour apprendre à travailler l’éclairage.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["photo-video"],"originalite":7,"asin":"B0CMWHB8Z5","univers":"photo-video","family":"reflecteur-photo","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CMWHB8Z5?tag=trouvetonca05-21"},
  {"id":266,"titre":"Housses de pluie photo JJC","emoji":"📷","desc":"Pour protéger le matériel pendant une sortie humide. Vérifier le gabarit boîtier-objectif ; ce n’est pas un caisson de plongée.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["photo-video","nature-outdoor"],"originalite":7,"asin":"B0963G9TVD","univers":"photo-video","family":"housse-pluie-photo","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0963G9TVD?tag=trouvetonca05-21"},
  {"id":267,"titre":"Kit studio NEEWER avec fond et éclairages","emoji":"📷","desc":"Pour aménager un espace de portrait ou de vidéo à domicile. Ensemble encombrant : vérifier la pièce, les accessoires inclus et les besoins du photographe.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["photo-video"],"originalite":7,"asin":"B01JRYJ9HY","univers":"photo-video","family":"studio-photo","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01JRYJ9HY?tag=trouvetonca05-21"},
  {"id":268,"titre":"Lecteur de cartes mémoire BENFEI 4 en 1","emoji":"📷","desc":"Pour transférer les photos de cartes mémoire vers un appareil compatible. Vérifier les formats de cartes et les connecteurs disponibles.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["photo-video","technologie"],"originalite":7,"asin":"B08P517NW5","univers":"photo-video","family":"lecteur-cartes","traits":["utile","passion"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08P517NW5?tag=trouvetonca05-21"},
  {"id":269,"titre":"Duo de mugs à peindre Home of creations","emoji":"🎨","desc":"Deux mugs à décorer pour créer des souvenirs assortis lors d’une activité à deux. Suivre les consignes de fixation et de contact alimentaire des peintures.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["creatif-diy","maison-deco"],"originalite":7,"asin":"B0GTRCGHRL","univers":"creatif-diy","family":"peinture-ceramique","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0GTRCGHRL?tag=trouvetonca05-21"},
  {"id":270,"titre":"Kit de modelage DIBYS à séchage à l’air","emoji":"🎨","desc":"Pour façonner à la main de petits objets décoratifs, sans tour de potier. Ne pas considérer les créations comme de la vaisselle alimentaire.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["creatif-diy","maison-deco"],"originalite":7,"asin":"B0CPD27KH3","univers":"creatif-diy","family":"modelage-argile","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0CPD27KH3?tag=trouvetonca05-21"},
  {"id":271,"titre":"Kit sculpture sur bois BeaverCraft Oiseau","emoji":"🎨","desc":"Pour découvrir la sculpture manuelle autour d’un projet guidé. Réservé aux adultes : outils tranchants, gestes et protections de la notice à respecter.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["creatif-diy","bricolage"],"originalite":7,"asin":"B07XY6KTVS","univers":"creatif-diy","family":"sculpture-bois","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07XY6KTVS?tag=trouvetonca05-21"},
  {"id":272,"titre":"Dessous de verre en mosaïque Kuvarix","emoji":"🎨","desc":"Trois supports à décorer avec des tesselles colorées. Une activité à partager pour fabriquer de petits objets pour la maison.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["creatif-diy","maison-deco"],"originalite":7,"asin":"B0G4CNH6V1","univers":"creatif-diy","family":"mosaique-decorative","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0G4CNH6V1?tag=trouvetonca05-21"},
  {"id":273,"titre":"Coffret peinture acrylique Zenacolor","emoji":"🎨","desc":"Peintures, toiles et pinceaux pour se lancer sur plusieurs petites compositions. Prévoir un plan de travail protégé et le temps de séchage.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["creatif-diy"],"originalite":7,"asin":"B08W29YJ5G","univers":"creatif-diy","family":"peinture-acrylique","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08W29YJ5G?tag=trouvetonca05-21"},
  {"id":274,"titre":"Coffret croquis graphite et fusain HIFORNY","emoji":"🎨","desc":"Pour explorer les ombres, les textures et les esquisses au crayon ou au fusain, avec les outils rangés dans un étui.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["creatif-diy"],"originalite":7,"asin":"B0FDQF53MQ","univers":"creatif-diy","family":"dessin-graphite","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0FDQF53MQ?tag=trouvetonca05-21"},
  {"id":275,"titre":"Kit création de bijoux en perles pour adulte","emoji":"🎨","desc":"Pour composer bracelets et colliers selon ses goûts. Les perles imitent notamment des pierres : aucune matière précieuse n’est promise.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["creatif-diy"],"originalite":7,"asin":"B0DLK3CCGH","univers":"creatif-diy","family":"bijoux-perles","traits":["creatif","experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DLK3CCGH?tag=trouvetonca05-21"}
,
  // Passe 1.6 — références qualifiées individuellement, budgets éditoriaux.
  {"id":276,"titre":"Piano des découvertes VTech","emoji":"🧸","desc":"Pour découvrir sons et touches en jouant, dès 9 mois. Un petit piano à explorer avec un adulte, sans le présenter comme adapté dès la naissance.","genre":["enfant"],"age":["0-3"],"budget":"20-50","interets":["musique"],"originalite":7,"asin":"B0F3DP4ZY1","univers":"musique","family":"piano-eveil","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0F3DP4ZY1?tag=trouvetonca05-21"},
  {"id":277,"titre":"Maxi-coffret de bain VTech","emoji":"🧸","desc":"Des accessoires pour transvaser et jouer dans le bain dès 12 mois. Toujours sous la surveillance rapprochée d’un adulte.","genre":["enfant"],"age":["0-3"],"budget":"20-50","interets":[],"originalite":7,"asin":"B0C86HDJQT","univers":"jeux-societe","family":"jeux-bain","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0C86HDJQT?tag=trouvetonca05-21"},
  {"id":278,"titre":"Ourson VTech 1, 2, 3 suis-moi","emoji":"🧸","desc":"Un ourson animé à suivre et observer, annoncé de 9 mois à 3 ans. Pour partager un jeu au sol dans un espace dégagé.","genre":["enfant"],"age":["0-3"],"budget":"20-50","interets":["animaux"],"originalite":7,"asin":"B00VFKBSZ0","univers":"animaux","family":"peluche-motricite","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00VFKBSZ0?tag=trouvetonca05-21"},
  {"id":279,"titre":"Camion de dépannage interactif VTech","emoji":"🧸","desc":"Un camion avec une rampe et de petites voitures pour inventer des dépannages. Dès 1 an, avec les précautions de la notice.","genre":["enfant"],"age":["0-3"],"budget":"20-50","interets":[],"originalite":7,"asin":"B0F3DNP4YR","univers":"jeux-societe","family":"vehicule-imitation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0F3DNP4YR?tag=trouvetonca05-21"},
  {"id":280,"titre":"Chariot magnétique Janod BricoKids","emoji":"🧸","desc":"Un atelier miniature mobile pour manipuler des outils de jeu. Dès 18 mois ; ce sont des jouets, pas des outils de bricolage réels.","genre":["enfant"],"age":["0-3"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B079TJ96MK","univers":"bricolage","family":"atelier-imitation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B079TJ96MK?tag=trouvetonca05-21"},
  {"id":281,"titre":"Descendeur fourmis Janod Sweet Cocoon","emoji":"🧸","desc":"Pour regarder les pièces dévaler la rampe et recommencer à son rythme. Un jeu de manipulation annoncé de 12 à 36 mois.","genre":["enfant"],"age":["0-3"],"budget":"20-50","interets":["animaux"],"originalite":7,"asin":"B0DTQ9T6B6","univers":"animaux","family":"rampe-manipulation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0DTQ9T6B6?tag=trouvetonca05-21"},
  {"id":282,"titre":"Dobble Kids","emoji":"🧸","desc":"Des animaux à repérer entre les cartes pour de courtes parties d’observation. Dès 4 ans, à découvrir ensemble avant de jouer en autonomie.","genre":["enfant"],"age":["4-7"],"budget":"<20","interets":["animaux"],"originalite":7,"asin":"B08R7VGQKY","univers":"animaux","family":"jeu-observation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08R7VGQKY?tag=trouvetonca05-21"},
  {"id":283,"titre":"Génération Mimes ZENAGAME","emoji":"🧸","desc":"Des cartes à faire deviner avec des gestes pour rire ensemble sans écran. Dès 4 ans, avec des niveaux à choisir selon les joueurs.","genre":["enfant"],"age":["4-7","8-12"],"budget":"<20","interets":[],"originalite":7,"asin":"B09M77XMR7","univers":"jeux-societe","family":"jeu-mime","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B09M77XMR7?tag=trouvetonca05-21"},
  {"id":284,"titre":"Croque Carotte Ravensburger","emoji":"🧸","desc":"Un jeu de parcours où les lapins avancent vers une carotte pleine de surprises. Dès 4 ans, pour partager une partie avec des proches.","genre":["enfant"],"age":["4-7"],"budget":"20-50","interets":["animaux"],"originalite":7,"asin":"B00BP4FRZI","univers":"animaux","family":"jeu-parcours","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00BP4FRZI?tag=trouvetonca05-21"},
  {"id":285,"titre":"Le Cochon qui rit Dujardin","emoji":"🧸","desc":"Lancer les dés et assembler son cochon au fil de la partie. Un jeu de manipulation et de hasard proposé dès 4 ans.","genre":["enfant"],"age":["4-7"],"budget":"<20","interets":["animaux"],"originalite":7,"asin":"B000VBPDIC","univers":"animaux","family":"jeu-assemblage","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B000VBPDIC?tag=trouvetonca05-21"},
  {"id":286,"titre":"Établi Smoby Black + Decker Bricolo Builder","emoji":"🧸","desc":"Un grand établi d’imitation pour inventer des travaux avec des accessoires de jeu. Fabricant : dès 3 ans ; retenu ici pour les 4–7 ans.","genre":["enfant"],"age":["4-7"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B0FCSRKCBC","univers":"bricolage","family":"atelier-imitation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0FCSRKCBC?tag=trouvetonca05-21"},
  {"id":287,"titre":"Cuisine Smoby Nova","emoji":"🧸","desc":"Une petite cuisine d’imitation pour préparer des repas imaginaires. Dès 18 mois ; vérifier les dimensions et la place disponible.","genre":["enfant"],"age":["0-3"],"budget":"20-50","interets":["cuisine"],"originalite":7,"asin":"B0C7WJJ6P4","univers":"cuisine","family":"cuisine-imitation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0C7WJJ6P4?tag=trouvetonca05-21"},
  {"id":288,"titre":"Centre vétérinaire Smoby","emoji":"🧸","desc":"Un coin de jeu pour examiner et soigner des animaux imaginaires. Annoncé dès 3 ans, retenu ici pour les 4–7 ans.","genre":["enfant"],"age":["4-7"],"budget":"50-100","interets":["animaux"],"originalite":7,"asin":"B0D8VZZDM6","univers":"animaux","family":"veterinaire-imitation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0D8VZZDM6?tag=trouvetonca05-21"},
  {"id":289,"titre":"Salon Smoby Barber & Cut","emoji":"🧸","desc":"Un salon d’imitation pour inventer coiffures et rendez-vous avec des accessoires de jeu. Dès 3 ans ; proposé ici aux 4–7 ans.","genre":["enfant"],"age":["4-7"],"budget":"50-100","interets":[],"originalite":7,"asin":"B0B2PD916P","univers":"jeux-societe","family":"coiffure-imitation","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0B2PD916P?tag=trouvetonca05-21"},
  {"id":290,"titre":"Machine Buki Professional Studio Couture","emoji":"🧸","desc":"Pour découvrir la couture et réaliser de premiers projets, dès 8 ans. L’aiguille et la machine nécessitent l’accompagnement d’un adulte.","genre":["enfant"],"age":["8-12","13-17"],"budget":"50-100","interets":["creatif-diy"],"originalite":7,"asin":"B07DLGLHNL","univers":"creatif-diy","family":"couture-machine","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07DLGLHNL?tag=trouvetonca05-21"},
  {"id":291,"titre":"Télescope Buki et activités d’astronomie","emoji":"🧸","desc":"Pour commencer à observer le ciel et explorer l’astronomie dès 8 ans, avec un adulte. Ne jamais pointer l’instrument vers le Soleil.","genre":["enfant"],"age":["8-12","13-17"],"budget":"50-100","interets":["nature-outdoor"],"originalite":7,"asin":"B071JDJDCT","univers":"nature-outdoor","family":"astronomie","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B071JDJDCT?tag=trouvetonca05-21"},
  {"id":292,"titre":"Outil multifonction Bosch PMF 220 CE","emoji":"🎁","desc":"Pour découper ou poncer dans des endroits difficiles d’accès avec l’accessoire adapté. Une idée pour un adulte déjà équipé des protections nécessaires.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B01D080ILY","univers":"bricolage","family":"outil-oscillant","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01D080ILY?tag=trouvetonca05-21"},
  {"id":293,"titre":"Ponceuse Bosch Texoro","emoji":"🎁","desc":"Pour travailler des surfaces profilées et préparer de petits projets de rénovation. Choisir les abrasifs et protections adaptés au matériau.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B08KGGTLKM","univers":"bricolage","family":"poncage-profile","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08KGGTLKM?tag=trouvetonca05-21"},
  {"id":294,"titre":"Décapeur thermique Bosch UniversalHeat 600","emoji":"🎁","desc":"Pour des travaux nécessitant une chaleur réglable, selon la notice. Réservé aux adultes habitués au bricolage, avec ventilation et précautions adaptées.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B07BWTDXG3","univers":"bricolage","family":"decapeur-thermique","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07BWTDXG3?tag=trouvetonca05-21"},
  {"id":295,"titre":"Défonceuse Bosch POF 1200 AE","emoji":"🎁","desc":"Pour réaliser rainures et finitions sur des projets en bois. Une idée destinée à un adulte expérimenté disposant d’un atelier adapté.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B000W34ZB0","univers":"bricolage","family":"defonceuse","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B000W34ZB0?tag=trouvetonca05-21"},
  {"id":296,"titre":"Établi pliant Black + Decker Workmate 825","emoji":"🎁","desc":"Un support de travail à installer pour maintenir les pièces pendant ses projets. Vérifier la place, la charge et les usages prévus dans la notice.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["bricolage"],"originalite":7,"asin":"B0001GRVYG","univers":"bricolage","family":"etabli-pliant","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0001GRVYG?tag=trouvetonca05-21"},
  {"id":297,"titre":"Étau d’établi Stanley 1-83-068","emoji":"🎁","desc":"Pour maintenir une pièce pendant les travaux manuels. À offrir à quelqu’un disposant d’un établi compatible pour sa fixation.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["bricolage"],"originalite":7,"asin":"B0015Q7D8U","univers":"bricolage","family":"etau-etabli","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0015Q7D8U?tag=trouvetonca05-21"},
  {"id":298,"titre":"Sacoche de réservoir moto X0SL12M","emoji":"🎁","desc":"Pour garder de petites affaires accessibles lors des trajets à moto. Vérifier impérativement la compatibilité du réservoir et de la fixation magnétique.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["auto-moto","voyage"],"originalite":7,"asin":"B019C9GWFQ","univers":"auto-moto","family":"sacoche-moto","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B019C9GWFQ?tag=trouvetonca05-21"},
  {"id":299,"titre":"Rouleau de nettoyage moto GRAND PITSTOP","emoji":"🎁","desc":"Un accessoire pour faciliter la rotation d’une roue pendant son entretien. Vérifier la compatibilité et suivre la notice, moteur arrêté.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["auto-moto"],"originalite":7,"asin":"B07JMZDDKV","univers":"auto-moto","family":"nettoyage-roue-moto","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07JMZDDKV?tag=trouvetonca05-21"},
  {"id":300,"titre":"Kit d’entretien de casque IPONE","emoji":"🎁","desc":"Pour entretenir son casque avec des produits dédiés. Vérifier leur compatibilité avec les matériaux et le traitement de la visière.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"<20","interets":["auto-moto"],"originalite":7,"asin":"B074KLHD3J","univers":"auto-moto","family":"entretien-casque","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B074KLHD3J?tag=trouvetonca05-21"},
  {"id":301,"titre":"Housse moto Oxford CV331","emoji":"🎁","desc":"Pour couvrir une moto lorsqu’elle est stationnée. Choisir après vérification des dimensions et suivre les précautions de pose sur le véhicule.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["auto-moto"],"originalite":7,"asin":"B01L8WAQRK","univers":"auto-moto","family":"housse-moto","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01L8WAQRK?tag=trouvetonca05-21"},
  {"id":302,"titre":"Lecteur diagnostic auto ANCEL AD410","emoji":"🎁","desc":"Un lecteur autonome pour consulter des codes moteur sur les véhicules compatibles. Vérifier l’OBD2 du véhicule ; il ne remplace pas un diagnostic professionnel.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["auto-moto","technologie"],"originalite":7,"asin":"B071FSNL73","univers":"auto-moto","family":"diagnostic-auto","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B071FSNL73?tag=trouvetonca05-21"},
  {"id":303,"titre":"Mini-polisseuse sans fil DCA 12 V","emoji":"🎁","desc":"Pour les petites surfaces et finitions d’entretien automobile avec les accessoires adaptés. S’exercer et vérifier la compatibilité du produit avec la surface.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["auto-moto","bricolage"],"originalite":7,"asin":"B0FCRQ7FKB","univers":"auto-moto","family":"polissage","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0FCRQ7FKB?tag=trouvetonca05-21"},
  {"id":304,"titre":"Caméra de route 70mai M310 Plus","emoji":"🎁","desc":"Pour enregistrer ses trajets avec une caméra dédiée. Vérifier installation et carte mémoire ; le mode parking demande un kit d’alimentation vendu séparément.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["auto-moto","technologie"],"originalite":7,"asin":"B0GKGSBWWH","univers":"auto-moto","family":"camera-route","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0GKGSBWWH?tag=trouvetonca05-21"},
  {"id":305,"titre":"Programmateur d’arrosage Gardena Master","emoji":"🌿","desc":"Pour programmer l’arrosage et organiser l’entretien de ses plantations. Vérifier le raccordement au robinet et la compatibilité de l’installation.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["jardinage"],"originalite":7,"asin":"B07JKZ9BPK","univers":"jardinage","family":"programmateur-arrosage","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07JKZ9BPK?tag=trouvetonca05-21"},
  {"id":306,"titre":"Désherbeur manuel Fiskars Ergonomic","emoji":"🌿","desc":"Pour retirer des mauvaises herbes avec un outil à manche. Une idée pratique pour un jardinier, à choisir selon le sol et les végétaux concernés.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["jardinage"],"originalite":7,"asin":"B0G7JQT5NF","univers":"jardinage","family":"desherbage-manuel","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0G7JQT5NF?tag=trouvetonca05-21"},
  {"id":307,"titre":"Coupe-branches Fiskars PowerGear L78","emoji":"🌿","desc":"Pour entretenir les arbustes avec un outil manuel dédié. Vérifier le diamètre de coupe admis et respecter les précautions d’élagage.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["jardinage"],"originalite":7,"asin":"B0017VF34O","univers":"jardinage","family":"elagage-manuel","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0017VF34O?tag=trouvetonca05-21"},
  {"id":308,"titre":"Pied d’éclairage photo NEEWER","emoji":"📷","desc":"Un support pour installer un éclairage lors de prises de vue. Lampe non incluse : vérifier la fixation et la charge compatibles avec son matériel.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["photo-video"],"originalite":7,"asin":"B0732VF22Z","univers":"photo-video","family":"pied-eclairage","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0732VF22Z?tag=trouvetonca05-21"},
  {"id":309,"titre":"Mini-trépied photo NEEWER","emoji":"📷","desc":"Pour stabiliser un appareil près du sol ou réaliser des prises de vue rapprochées. Vérifier le poids du matériel et la fixation avant de choisir.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["photo-video"],"originalite":7,"asin":"B07FKDH3BC","univers":"photo-video","family":"trepied-photo-bas","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B07FKDH3BC?tag=trouvetonca05-21"},
  {"id":310,"titre":"Éclairage compact ULANZI VL49 RGB","emoji":"📷","desc":"Une petite lumière colorée pour expérimenter en photo ou vidéo à courte distance. Un complément créatif plutôt qu’un éclairage de studio complet.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"20-50","interets":["photo-video"],"originalite":7,"asin":"B08PYN6LWP","univers":"photo-video","family":"eclairage-photo-compact","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B08PYN6LWP?tag=trouvetonca05-21"},
  {"id":311,"titre":"Machine Sizzix Big Shot","emoji":"🎁","desc":"Pour découper et gaufrer dans ses projets de papier créatif. Vérifier les matrices compatibles à prévoir séparément et le contenu exact du coffret.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":">100","interets":["creatif-diy"],"originalite":7,"asin":"B0FNRQNMV5","univers":"creatif-diy","family":"decoupe-gaufrage","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0FNRQNMV5?tag=trouvetonca05-21"},
  {"id":312,"titre":"Station de pyrogravure XIIW","emoji":"🎁","desc":"Pour décorer le bois avec un outil chauffant et explorer le dessin gravé. Usage adulte avec ventilation, support adapté et précautions de la notice.","genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["creatif-diy","bricolage"],"originalite":7,"asin":"B0B71LL8H7","univers":"creatif-diy","family":"pyrogravure","traits":["utile"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0B71LL8H7?tag=trouvetonca05-21"},
  {"id":313,"titre":"Yaourtière Lagrange sept pots","emoji":"🍽️","desc":"Pour préparer des yaourts maison et choisir ensemble les recettes. Une idée à partager pour un couple qui aime cuisiner et prévoir ses petits déjeuners.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["cuisine"],"originalite":7,"asin":"B002KD9OGQ","univers":"cuisine","family":"yaourtiere","traits":["experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B002KD9OGQ?tag=trouvetonca05-21"},
  {"id":314,"titre":"Sorbetière Lagrange 409021","emoji":"🍽️","desc":"Pour préparer des glaces et sorbets à partager en variant les parfums. Prévoir la préparation de la cuve selon la notice et la place nécessaire.","genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"budget":"50-100","interets":["cuisine"],"originalite":7,"asin":"B01HCX9VVQ","univers":"cuisine","family":"sorbetiere","traits":["experience_maison"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01HCX9VVQ?tag=trouvetonca05-21"}
,
  {"id":315,"titre":"Imprimante photo Canon Selphy CP1500","desc":"Pour imprimer des souvenirs à garder ou à offrir ensemble. Papier et recharge non inclus : prévoir les consommables compatibles.","emoji":"🎁","budget":">100","interets":["photo-video"],"genre":["homme","femme","couple"],"age":["18-25","26-35","36-50","50+"],"family":"impression-photo","originalite":7,"asin":"B0BBMX16RG","univers":"photo-video","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B0BBMX16RG?tag=trouvetonca05-21"},
  {"id":316,"titre":"Hamac Amazonas Moskito-Traveller","desc":"Pour une pause en plein air avec moustiquaire. Vérifier la charge indiquée sur la notice, les fixations à prévoir et les points d’ancrage adaptés.","emoji":"🎁","budget":"50-100","interets":["nature-outdoor","voyage"],"genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"family":"hamac-outdoor","originalite":7,"asin":"B00024BIPU","univers":"nature-outdoor","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00024BIPU?tag=trouvetonca05-21"},
  {"id":317,"titre":"Station météo TFA Spring Breeze","desc":"Pour suivre la température et le vent autour de la maison. Installer le capteur selon la notice ; les tendances affichées ne sont pas des garanties météo.","emoji":"🎁","budget":"50-100","interets":["maison-deco","jardinage"],"genre":["homme","femme"],"age":["18-25","26-35","36-50","50+"],"family":"station-meteo","originalite":7,"asin":"B01LWZ5RNY","univers":"maison-deco","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B01LWZ5RNY?tag=trouvetonca05-21"},
  {"id":318,"titre":"Théâtre de marionnettes roba","desc":"Un petit théâtre avec six personnages pour inventer et jouer des histoires. Dès 3 ans ; proposé ici aux 4–7 ans, après vérification de la place disponible.","emoji":"🧸","budget":"50-100","interets":["creatif-diy"],"genre":["enfant"],"age":["4-7"],"family":"theatre-marionnettes","originalite":7,"asin":"B00067AEQM","univers":"creatif-diy","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B00067AEQM?tag=trouvetonca05-21"},
  {"id":319,"titre":"Animaux magnétiques SmartMax My First Safari","desc":"Des animaux à assembler ou mélanger pour imaginer de nouvelles créatures. Annoncé de 1 à 5 ans ; proposé ici aux tout-petits dès 12 mois.","emoji":"🧸","budget":"20-50","interets":["animaux"],"genre":["enfant"],"age":["0-3"],"family":"construction-magnetique","originalite":7,"asin":"B06Y3V1WXG","univers":"animaux","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B06Y3V1WXG?tag=trouvetonca05-21"},
  {"id":320,"titre":"Poupon Corolle Bébé Calin Manon","desc":"Un poupon souple pour les premiers jeux d’imitation et les histoires du quotidien. Dès 18 mois ; une idée à choisir selon les envies de l’enfant.","emoji":"🧸","budget":"20-50","interets":[],"genre":["enfant"],"age":["0-3"],"family":"poupon-imitation","originalite":7,"asin":"B082GM14LF","univers":"jeux-societe","traits":["decouverte"],"occasions":["anniv","noel"],"image":"","imageFallback":true,"affiliateLink":"https://www.amazon.fr/dp/B082GM14LF?tag=trouvetonca05-21"}
];
