'use strict';
const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.TTC_BROWSER_CHANNEL || 'msedge'});
  const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});
  await context.route('**/*',route=>{
    const u=new URL(route.request().url());
    if(['127.0.0.1','localhost'].includes(u.hostname)||u.protocol==='data:')return route.continue();
    return route.fulfill({status:200,body:'',contentType:route.request().resourceType()==='script'?'application/javascript':'text/plain'});
  });
  const page=await context.newPage(),errors=[],localFailures=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  page.on('response',r=>{if(r.url().startsWith('http://127.0.0.1')&&r.status()>=400)localFailures.push(r.url())});
  await page.goto('http://127.0.0.1:4173/');
  await page.waitForFunction(()=>typeof CADEAUX!=='undefined'&&CADEAUX.length===320);
  await page.locator('[data-key="genre"][data-value="homme"]').click();
  await page.locator('#next-1').click();
  await page.locator('[data-key="age"][data-value="26-35"]').click();
  await page.locator('#next-2').click();
  await page.locator('[data-key="budget"][data-value="20-50"]').click();
  await page.locator('#next-3').click();
  await page.locator('.interest-btn[data-value="technologie"]').click();
  await page.locator('.interest-btn[data-value="lecture"]').click();
  await page.locator('.btn-submit').click();
  await page.locator('#cardsGrid .gift-card').first().waitFor();
  assert.equal(await page.locator('#cardsGrid .gift-card').count(),10);
  assert.ok(await page.locator('#cardsGrid .card-why').count()>0);
  assert.equal(await page.locator('#cardsGrid .card-why-list li').first().count(),1);
  const cards=page.locator('#cardsGrid .gift-card');
  for(let i=0;i<3;i++)await cards.nth(i).locator('.btn-compare-gifts').click();
  assert.deepEqual(await page.evaluate(()=>comparisonIds.length),3);
  await cards.nth(3).locator('.btn-compare-gifts').click();
  assert.equal(await page.evaluate(()=>comparisonIds.length),3,'limite de trois');
  await page.locator('#compareResultsBtn').click();
  assert.equal(await page.locator('#compareGrid .compare-card').count(),3);
  const links=await page.locator('#compareGrid .btn-buy').evaluateAll(elements=>elements.map(el=>({href:el.href,rel:el.rel})));
  for(const link of links){assert.match(link.href,/\/dp\/[A-Z0-9]{10}\?tag=trouvetonca05-21/);assert.equal(link.rel,'noopener noreferrer sponsored')}
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#compareModal').isVisible(),false);
  await cards.nth(0).locator('.btn-compare-gifts').click();
  assert.equal(await page.evaluate(()=>comparisonIds.length),2);
  await page.locator('#compareResultsBtn').click();
  assert.equal(await page.locator('#compareGrid .compare-card').count(),2);
  await page.locator('#compareGrid .compare-card').first().getByRole('button',{name:'Retirer de la comparaison'}).click();
  assert.equal(await page.locator('#compareGrid .compare-card').count(),1);
  await page.keyboard.press('Escape');
  await cards.nth(4).locator('.btn-fav').click();
  await cards.nth(4).locator('.btn-final-choice').click();
  const chosen=Number(await cards.nth(4).getAttribute('data-gift-id'));
  assert.equal(await page.evaluate(()=>localStorage.getItem('ttc_final_choice_v1')),String(chosen));
  await cards.nth(5).locator('.btn-final-choice').click();
  assert.equal(await page.evaluate(()=>getFinalChoiceId()),Number(await cards.nth(5).getAttribute('data-gift-id')));
  await cards.nth(4).locator('.btn-final-choice').click();
  assert.equal(await page.evaluate(()=>getFinalChoiceId()),chosen);
  await page.locator('#btnOpenFavorites').click();
  assert.ok((await page.locator('#finalChoiceBox').textContent()).includes('Mon choix'));
  await page.locator('#favGrid .btn-compare-gifts').first().click();
  assert.ok(await page.locator('#compareFavoritesBtn').isVisible());
  await page.locator('#compareFavoritesBtn').click();
  assert.equal(await page.locator('#compareGrid .compare-card').count(),2);
  assert.equal(await page.locator('#favModal').evaluate(el=>el.inert),true);
  await page.keyboard.press('Shift+Tab');
  assert.ok(await page.locator('#compareModal .modal-footer button').evaluate(el=>el===document.activeElement));
  await page.keyboard.press('Tab');
  assert.ok(await page.locator('#compareModal .modal-close').evaluate(el=>el===document.activeElement));
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#favModal').isVisible(),true);
  assert.equal(await page.locator('#favModal').evaluate(el=>el.inert),false);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#favModal').isVisible(),false);
  await page.reload();
  assert.equal(await page.evaluate(()=>getFinalChoiceId()),chosen);
  await page.locator('.header-nav button').click();
  assert.ok(await page.locator('#finalChoiceBox').isVisible());
  await page.locator('#finalChoiceBox button').click();
  assert.equal(await page.evaluate(()=>getFinalChoiceId()),null);
  await page.keyboard.press('Escape');
  await page.evaluate(id=>toggleCompareGift(id),chosen);
  for(const width of [390,768,1280])for(const theme of ['light','dark']){
    await page.setViewportSize({width,height:844});
    await page.evaluate(theme=>applyTheme(theme),theme);
    await page.evaluate(()=>openCompareModal());
    assert.ok(await page.locator('#compareModal').isVisible());
    const geometry=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,modal:document.querySelector('#compareModal .modal-box').getBoundingClientRect().right}));
    assert.ok(geometry.scroll<=geometry.viewport && geometry.modal<=geometry.viewport+1,JSON.stringify({width,theme,geometry}));
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#compareModal').isVisible(),false);
  }
  assert.deepEqual(errors,[]);assert.deepEqual(localFailures,[]);
  console.log(JSON.stringify({status:'PASS',compare:[1,2,3],limit:3,favorites:true,finalChoice:true,viewports:[390,768,1280],themes:['light','dark'],consoleErrors:errors,localFailures}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
