'use strict';
const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
  const browser = await chromium.launch({headless:true,channel:process.env.TTC_BROWSER_CHANNEL || 'msedge'});
  const context = await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});
  await context.route('**/*',route=>{
    const u=new URL(route.request().url());
    if(['127.0.0.1','localhost'].includes(u.hostname)||u.protocol==='data:') return route.continue();
    return route.fulfill({status:200,body:'',contentType:route.request().resourceType()==='script'?'application/javascript':'text/plain'});
  });
  const page=await context.newPage(), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto('http://127.0.0.1:4173/');
  await page.waitForFunction(()=>typeof CADEAUX!=='undefined'&&CADEAUX.length===320);
  for(const width of [390,768,1280]) for(const theme of ['light','dark']){
    await page.setViewportSize({width,height:844});
    await page.evaluate(theme=>{restartQuiz();applyTheme(theme);},theme);
    await page.locator('[data-key="genre"][data-value="homme"]').click();
    await page.locator('#next-1').click();
    await page.locator('[data-key="age"][data-value="26-35"]').click();
    await page.locator('#next-2').click();
    await page.locator('[data-key="budget"][data-value="20-50"]').click();
    await page.locator('#next-3').click();
    assert.equal(await page.evaluate(()=>state.currentStep),4);
    assert.equal(await page.locator('#unknownFollowup').isVisible(),false);
    const unknown=page.locator('.interest-btn[data-value="unknown"]');
    await unknown.evaluate(el=>el.scrollIntoView({block:'end',behavior:'instant'}));
    const box=await unknown.boundingBox();
    await page.mouse.click(box.x+box.width/2,box.y+box.height/2);
    assert.equal(await page.locator('#unknownFollowup').isVisible(),true);
    const bounds=await page.locator('.unknown-question p').evaluateAll(nodes=>nodes.map(n=>({top:n.getBoundingClientRect().top,bottom:n.getBoundingClientRect().bottom,viewport:innerHeight})));
    assert.ok(bounds.every(b=>b.top>=0&&b.bottom<=b.viewport),'questions hors écran avant génération : '+JSON.stringify({width,theme,bounds}));
    await page.locator('[data-unknown-key="person"][data-value="tech"]').click();
    await page.locator('[data-unknown-key="gift"][data-value="useful"]').click();
    assert.deepEqual(await page.evaluate(()=>[state.unknownPerson,state.unknownGift]),['tech','useful']);
    assert.equal(await page.locator('.unknown-option-btn.selected').count(),2);
    await page.locator('[data-unknown-key="gift"][data-value="useful"]').click();
    assert.deepEqual(await page.evaluate(()=>[state.unknownPerson,state.unknownGift]),['tech',null]);
    await page.locator('[data-unknown-key="gift"][data-value="useful"]').click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'débordement '+width+' '+theme);
    await page.locator('.interest-btn[data-value="bricolage"]').click();
    assert.equal(await page.locator('#unknownFollowup').isVisible(),false);
    assert.deepEqual(await page.evaluate(()=>[state.unknownPerson,state.unknownGift]),[null,null]);
    await page.locator('.interest-btn[data-value="unknown"]').click();
    assert.equal(await page.locator('.unknown-option-btn.selected').count(),0);
    assert.deepEqual(await page.evaluate(()=>[state.unknownPerson,state.unknownGift]),[null,null]);
    await page.locator('[data-unknown-key="person"][data-value="none"]').click();
    await page.locator('[data-unknown-key="gift"][data-value="none"]').click();
    assert.deepEqual(await page.evaluate(()=>[state.unknownPerson,state.unknownGift]),['none','none']);
    await page.locator('.btn-submit').click();
    await page.locator('#cardsGrid .gift-card').first().waitFor();
    assert.ok(await page.locator('#cardsGrid .gift-card').count()>0);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'résultats débordants '+width+' '+theme);
  }
  // Parcours complet distinct : les deux réponses choisies atteignent le moteur avant la génération.
  await page.evaluate(()=>localStorage.clear());
  await page.reload();
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-key="genre"][data-value="homme"]').click();
  await page.locator('#next-1').click();
  await page.locator('[data-key="age"][data-value="26-35"]').click();
  await page.locator('#next-2').click();
  await page.locator('[data-key="budget"][data-value="20-50"]').click();
  await page.locator('#next-3').click();
  const unknown=page.locator('.interest-btn[data-value="unknown"]');
  await unknown.evaluate(el=>el.scrollIntoView({block:'end',behavior:'instant'}));
  const box=await unknown.boundingBox();
  await page.mouse.click(box.x+box.width/2,box.y+box.height/2);
  assert.equal(await page.locator('#unknownFollowup').isVisible(),true);
  await page.locator('[data-unknown-key="person"][data-value="tech"]').click();
  await page.locator('[data-unknown-key="gift"][data-value="useful"]').click();
  const rankings=await page.evaluate(()=>{
    Math.random=()=>0;
    const ranked=(person,gift)=>GiftEngine.select(CADEAUX,{...state,unknownPerson:person,unknownGift:gift},recommendationMemory,{random:()=>0}).results.map(g=>g.id);
    return {none:ranked(null,null),person:ranked('tech',null),gift:ranked(null,'useful'),both:ranked('tech','useful')};
  });
  assert.notDeepEqual(rankings.person,rankings.none);
  assert.notDeepEqual(rankings.gift,rankings.none);
  assert.notDeepEqual(rankings.both,rankings.none);
  await page.locator('.btn-submit').click();
  await page.locator('#cardsGrid .gift-card').first().waitFor();
  assert.deepEqual(await page.evaluate(()=>displayedIds),rankings.both);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({status:'PASS',viewports:[390,768,1280],themes:['light','dark'],consoleErrors:errors}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
